FROM golang:1.17 AS build

ARG FRP_VERSION=0.38.0

USER root
WORKDIR /root

RUN cd /root \
    && git clone https://github.com/fatedier/frp.git --depth=1 --branch=${FRP_VERSION} \
    && cd frp \
    make frps

FROM alpine:3.15

COPY --from=build /root/frp/bin/frps /usr/bin/frps
COPY --from=build /root/frp/conf/frps.ini /etc/frp/frps.ini

ENTRYPOINT /usr/bin/frps -c /etc/frp/frps.ini
