FROM golang:1.17 AS build

ARG FRP_VERSION=0.38.0

USER root
WORKDIR /root

RUN cd /root \
    && git clone https://github.com/fatedier/frp.git --depth=1 --branch=${FRP_VERSION} \
    && cd frp \
    make frpc

FROM alpine:3.15

COPY --from=build /root/frp/bin/frpc /usr/bin/frpc
COPY --from=build /root/frp/conf/frpc.ini /etc/frp/frpc.ini

ENTRYPOINT /usr/bin/frpc -c /etc/frp/frpc.ini
