# yaml-language-server: $schema=https://json-schema.org/draft-07/schema#
name: Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: 'dev'
      frpc-tags:
        description: 'frpc-tags'
        required: true
        default: 'dup4/frpc:latest'
      frps-tags:
        description: 'frps-tags'
        required: true
        default: 'dup4/frps:latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frpc
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
          build-args: |
            "FRP_VERSION=${{ github.event.inputs.version }}"
            "MODE=frpc"
          push: true
          tags: ${{ github.event.inputs.frpc-tags }}

      - name: Build and Push Frps
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/mips64le,linux/mips64,linux/arm/v7,linux/arm/v6
          build-args: |
            "FRP_VERSION=${{ github.event.inputs.version }}"
            "MODE=frps"
          push: true
          tags: ${{ github.event.inputs.frps-tags }}
